### ISSUE TITLE
Not able to move around the hoverMesh in Editor

### ISSUE THREAD

**Issue by alexus85** [vonWolfehaus/von-grid#16]
Not sure why , but the **hoverMesh** can only move along one axis in Editor. (Master branch) .

It works however in the public [example](http://vonwolfehaus.github.io/von-grid/editor/).

Tested in both Chrome and FF browsers.

**Comment by alexus85** [comment]
changed the z and y coordinates  for to the `editorWorldPos` in `Input.update` and the `hoverMesh`started moving around properly. 

```
if (hit) {// flip things around a little to fit to our rotated grid
                this.editorWorldPos.x = hit.point.x;
                this.editorWorldPos.y = hit.point.y; // grids are rotated on axis so that objects keep their y+ orientation
                this.editorWorldPos.z = hit.point.z;
            }
```

**Comment by vonWolfehaus** [comment]
Thanks, I updated it in the master branch. I didn't update the build though, so you'll have to run `gulp`. You might want to check out the `dev` branch since it's a bit cleaner code. Although I'm not sure how stable it is, but it's the API that will be used eventually, if you're worried about forward compatibility.
