### ISSUE TITLE
grid navigation

### ISSUE THREAD

**Issue by shopapps** [vonWolfehaus/von-grid#18]
Hi,  I just come across this great looking bit of code, and apologies if this is not the correct place to ask this question, however:

I would like to have a player "roll a dice" to determine straight line movement around the board.  If a player is starting in the centre of the board 0,0,0 and rolls dice for direction (D6) (1 is top-right, 2 is right, 3 is bottom right etc)  and distance (D6) what is the best method for calculating the destination tile?    the dice bit i can figure out it's calculating straight lines to the dest tile I havent got my head around yet...  

I was also wondering if there is a method to display each tiles coords on the board to help me figure out some of the maths of wrapping off the end of the board back onto the other side??

and finally...  :-) whats the difference between cell and tile in your code?

**Comment by vonWolfehaus** [comment]
Hello. I recommend getting familiar with hexagon [cube coordinates](http://www.redblobgames.com/grids/hexagons) since that's what I use as a basis for the grid. More specifically, in `HexGrid.js` you can see that I have a cached property `_directions` (also `_diagonals`) that you can use to find the neighboring tile in the direction you want to go in, and then simply adding the `Cell` values within those arrays to keep going for whatever distance you wish.

There's a lot of Threejs tutorials on how to display text in a way that always faces the camera - I recommend digging one of those up. Once you have the text showing, you could modify the `Tile.js` class to create the text object and attach it to the `THREE.Mesh` the `Tile` uses, or at least copy its `position` Vector3.

Be sure to use the `dev` branch - the difference is much more clear there. A `Cell` is simply the position and other data that's relevant to the grid classes for their own use. A `Tile` is the actual 3D mesh that copies the cell's position for displaying in the correct place.

If this answered your questions, please close this issue, I'd appreciate it.

**Comment by vonWolfehaus** [comment]
Since it's been a while I'll close this, but feel free to ask for any clarifications here.
