### ISSUE TITLE
Some bugs in SquareGrid

### ISSUE THREAD

**Issue by CLTanuki** [vonWolfehaus/von-grid#8]
1. No _geoCache in vg.SquareGrid. Solved by adding "this._geoCache = [];" to SquareGrid constructor.
2. Null x property on line 102 then.
   Probably solved by changing method:
   cellToPixel: function(c, pos) {
       this._vec3.x = c.q + (this.cellSize/2);
       this._vec3.y = c.h + (c.depth/2);
       this._vec3.z = c.s - (this.cellSize/2);
       return this._vec3;
   },
3. Then got "Uncaught TypeError: Cannot read property 'center' of undefined" on line 135 of three.js

**Comment by vonWolfehaus** [comment]
Yeah, the square grid is not at all maintained at the moment. Once I feel
comfortable with the generic grid API that all grids will use, I'll update
the square one to match. Otherwise more bugs will get introduced easily if
I try to keep it up with the hex grid. Sorry for the inconvenience! I'll
close this ticket once it's been updated.

**Comment by CLTanuki** [comment]
For some reasons we've choosed square grid for our game and it's being developed actively at the moment=) Are there some elder (but working) versions of square grid just to test some thouts?

**Comment by vonWolfehaus** [comment]
Ah, you know what, I'll go ahead and update the square grid since I don't
know when I'll get around to it otherwise, and I don't want to leave anyone
hanging. It seems enough people are following this library that I need to
have full functionality in master at least :) I'll ping you when it's
complete.

// corey

**Comment by vonWolfehaus** [comment]
@CLTanuki It turned out to be a lot easier than I thought, so the square grid is now usable in `master`. I only ran all the examples - there might be some hidden bugs, but if that's the case, please let me know.

There is one major bug, where the grid does not place tiles correctly if you change the `cellSize` to anything other than 10... I'll fix that one as soon as I can.
